# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

version: 0.0.{build}

branches:
  only:
  - master
skip_non_tags: false
skip_commits:
  message: /updated readme.*|update readme.*s/

environment:
  APIKEY:
    secure: djLw2n2x5RZApaETQrojq5DLYGVIcNqKlR2K1/w76XCwS8CcH2LxL1GBYkWUnQ5H

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\Build.ps1 -BuildInstallTestAndPublishModule